export const urlPage = {
  HOME: '/discover',
  PLAYLIST: '/playlist',
  PLAYLIST_CREATE: '/playlist/create',
  PLAYLIST_LIKES: '/playlist/likes',
  PLAYLIST_COLLAB: '/playlist/collaboration',
  PLAYLIST_DETAIL: '/playlist-detail',
  LIBRARY: '/you',
  SONG: '/song',
  ALBUM: '/album',
  LIBRARY_SONG: '/you/song',
  LIBRARY_SONG_CREATE: '/you/song/create',
  LIBRARY_SONG_LIKES: '/you/likes',
  LIBRARY_ALBUM: '/you/album',
  LIBRARY_ALBUM_CREATE: '/you/album/create',
  SEARCH: '/search',
  SEARCH_ALBUM: '/search/albums',
  SEARCH_PLAYLIST: '/search/playlists',
};

export const MODAL_TYPES = {
  LOGOUT: 'logout',
  DELETE: 'delete',
  USER_GOOGLE_FORM: 'userGoogleForm',
  LOGIN_FORM: 'loginForm',
  CREATE_SONG_FORM: 'createSongForm',
  UPDATE_SONG_FORM: 'updateSongForm',
  CREATE_ALBUM_FORM: 'createAlbumForm',
  UPDATE_ALBUM_FORM: 'updateAlbumForm',
  GOOGLE_LOGIN_FORM: 'googleLoginForm',
  PLAYLIST_FORM: 'playlistForm',
  PLAYLIST_ACTIVITIES: 'playlistActivities',
} as const;
