export const albums = [
  {
    id: '1',
    title: 'SOS',
    year: 2022,
    coverUrl: 'https://picsum.photos/200/600',
    songCount: '23',
    totalDuration: '68',
  },
  {
    id: '2',
    title: 'The Record',
    year: 2023,
    coverUrl: 'https://picsum.photos/300/600',
    songCount: '12',
    totalDuration: '42',
  },
  {
    id: '3',
    title: 'Guts',
    year: 2023,
    coverUrl: 'https://picsum.photos/220/600',
    songCount: '12',
    totalDuration: '39',
  },
  {
    id: '4',
    title: 'Let’s Start Here',
    year: 2023,
    coverUrl: 'https://picsum.photos/600/600',
    songCount: '14',
    totalDuration: '57',
  },
  {
    id: '5',
    title: 'Fountain Baby',
    year: 2023,
    coverUrl: 'https://picsum.photos/250/600',
    songCount: '14',
    totalDuration: '45',
  },
  {
    id: '6',
    title: 'False Lankum',
    year: 2023,
    coverUrl: 'https://picsum.photos/280/600',
    songCount: '12',
    totalDuration: '66',
  },
  {
    id: '7',
    title: 'The Rise and Fall of a Midwest Princess',
    year: 2023,
    coverUrl: 'https://picsum.photos/270/600',
    songCount: '14',
    totalDuration: '49',
  },
  {
    id: '8',
    title: 'Sundial',
    year: 2023,
    coverUrl: 'https://picsum.photos/290/600',
    songCount: '11',
    totalDuration: '33',
  },
  {
    id: '9',
    title: 'DeBí TiRAR MáS FOToS',
    year: 2023,
    coverUrl: 'https://picsum.photos/310/600',
    songCount: '17',
    totalDuration: '60',
  },
  {
    id: '10',
    title: 'If You Asked for a Picture',
    year: 2024,
    coverUrl: 'https://picsum.photos/320/600',
    songCount: '9',
    totalDuration: '36',
  },
  {
    id: '11',
    title: 'Tsunami Sea',
    year: 2024, // Asumsi fiktif
    coverUrl: 'https://picsum.photos/330/600',
    songCount: '10',
    totalDuration: '40',
  },
  {
    id: '12',
    title: 'Sable, Fable',
    year: 2024, // Asumsi fiktif
    coverUrl: 'https://picsum.photos/340/600',
    songCount: '12',
    totalDuration: '50',
  },
];

export const songs = [
  {
    id: '1',
    title: 'Not Like Us',
    year: 2024,
    performer: 'Kendrick Lamar',
    genre: 'Hip-Hop',
    duration: 274, // 4 minutes 34 seconds in seconds
    coverUrl: 'https://picsum.photos/100/300',
    albumId: '1',
  },
  {
    id: '2',
    title: 'Luther',
    year: 2024,
    performer: 'Kendrick Lamar feat. SZA',
    genre: 'Hip-Hop',
    duration: 252, // 4 minutes 12 seconds in seconds
    coverUrl: 'https://picsum.photos/200/300',
    albumId: '1',
  },
  {
    id: '3',
    title: 'Messy',
    year: 2023,
    performer: 'Lola Young',
    genre: 'Alternative',
    duration: 284, // 4 minutes 44 seconds in seconds
    coverUrl: 'https://picsum.photos/110/300',
    albumId: '2',
  },
  {
    id: '4',
    title: 'APT.',
    year: 2024,
    performer: 'ROSÉ & Bruno Mars',
    genre: 'Pop',
    duration: 179, // 2 minutes 59 seconds in seconds
    coverUrl: 'https://picsum.photos/130/300',
    albumId: '3',
  },
  {
    id: '5',
    title: 'Die With A Smile',
    year: 2024,
    performer: 'Lady Gaga & Bruno Mars',
    genre: 'Pop',
    duration: 195, // 3 minutes 15 seconds in seconds
    coverUrl: 'https://picsum.photos/140/300',
    albumId: '4',
  },
  {
    id: '6',
    title: 'Denial Is A River',
    year: 2024,
    performer: 'Doechii',
    genre: 'Hip-Hop',
    duration: 249, // 4 minutes 9 seconds in seconds
    coverUrl: 'https://picsum.photos/150/300',
    albumId: '5',
  },
  {
    id: '7',
    title: 'Good Luck, Babe!',
    year: 2023,
    performer: 'Chappell Roan',
    genre: 'Pop',
    duration: 218, // 3 minutes 38 seconds in seconds
    coverUrl: 'https://picsum.photos/160/300',
    albumId: '6',
  },
  {
    id: '8',
    title: 'Pink Pony Club',
    year: 2023,
    performer: 'Chappell Roan',
    genre: 'Pop',
    duration: 258, // 4 minutes 18 seconds in seconds
    coverUrl: 'https://picsum.photos/170/300',
    albumId: '6',
  },
  {
    id: '9',
    title: 'Baile Inolvidable',
    year: 2024,
    performer: 'Bad Bunny',
    genre: 'Reggaeton',
    duration: 230, // 3 minutes 50 seconds in seconds
    coverUrl: 'https://picsum.photos/180/300',
    albumId: '7',
  },
  {
    id: '10',
    title: 'Nokia',
    year: 2024,
    performer: 'Drake feat. PartyNextDoor',
    genre: 'R&B',
    duration: 202, // 3 minutes 22 seconds in seconds
    coverUrl: 'https://picsum.photos/190/300',
    albumId: '8',
  },
  {
    id: '11',
    title: 'Ordinary',
    year: 2024,
    performer: 'Alex Warren',
    genre: 'Pop',
    duration: 183, // 3 minutes 3 seconds in seconds
    coverUrl: 'https://picsum.photos/200/300',
    albumId: '9',
  },
  {
    id: '12',
    title: 'Sports Car',
    year: 2024,
    performer: 'Tate McRae',
    genre: 'Pop',
    duration: 190, // 3 minutes 10 seconds in seconds
    coverUrl: 'https://picsum.photos/210/300',
    albumId: '10',
  },
  {
    id: '13',
    title: 'Burning Blue',
    year: 2024,
    performer: 'Mariah The Scientist',
    genre: 'R&B',
    duration: 205, // 3 minutes 25 seconds in seconds
    coverUrl: 'https://picsum.photos/220/300',
    albumId: '11',
  },
  {
    id: '14',
    title: 'Tweaker',
    year: 2024,
    performer: 'LiAngelo Ball',
    genre: 'Hip-Hop',
    duration: 175, // 2 minutes 55 seconds in seconds
    coverUrl: 'https://picsum.photos/230/300',
    albumId: '12',
  },
  {
    id: '15',
    title: 'Anxiety',
    year: 2024,
    performer: 'Doechii',
    genre: 'Hip-Hop',
    duration: 249, // 4 minutes 9 seconds in seconds
    coverUrl: 'https://picsum.photos/240/300',
    albumId: '5',
  },
  {
    id: '16',
    title: 'Café Con Ron',
    year: 2024,
    performer: 'Bad Bunny feat. Pleneros de la Cresta',
    genre: 'Reggaeton',
    duration: 220, // 3 minutes 40 seconds in seconds
    coverUrl: 'https://picsum.photos/250/300',
    albumId: '7',
  },
  {
    id: '17',
    title: "I'm The Problem",
    year: 2024,
    performer: 'Morgan Wallen feat. Tate McRae',
    genre: 'Country',
    duration: 185, // 3 minutes 5 seconds in seconds
    coverUrl: 'https://picsum.photos/270/300',
    albumId: '13',
  },
  {
    id: '18',
    title: 'The Giver',
    year: 2023,
    performer: 'Chappell Roan',
    genre: 'Pop',
    duration: 210, // 3 minutes 30 seconds in seconds
    coverUrl: 'https://picsum.photos/260/300',
    albumId: '14',
  },
  {
    id: '19',
    title: 'Crybaby',
    year: 2024,
    performer: 'SZA',
    genre: 'R&B',
    duration: 225, // 3 minutes 45 seconds in seconds
    coverUrl: 'https://picsum.photos/270/300',
    albumId: '15',
  },
  {
    id: '20',
    title: 'Esa Noche',
    year: 2024,
    performer: 'Eslabón Armado feat. Macario Martínez',
    genre: 'Regional Mexican',
    duration: 240, // 4 minutes in seconds
    coverUrl: 'https://picsum.photos/290/300',
    albumId: '16',
  },
  {
    id: '21',
    title: 'Rather Lie',
    year: 2024,
    performer: 'Playboi Carti feat. The Weeknd & Keith Lawson',
    genre: 'Hip-Hop',
    duration: 200, // 3 minutes 20 seconds in seconds
    coverUrl: 'https://picsum.photos/400/300',
    albumId: '17',
  },
  {
    id: '22',
    title: 'Nice to Each Other',
    year: 2023,
    performer: 'Olivia Dean',
    genre: 'Pop',
    duration: 195, // 3 minutes 15 seconds in seconds
    coverUrl: 'https://picsum.photos/222/300',
    albumId: '18',
  },
];

export const playlists = [
  {
    id: 'playlist-rurCL1SOIgbUStup',
    title: 'Lagu Indie Hits Indonesia',
    fullname: 'sueb',
    songCount: '12',
    totalDuration: '230',
  },
  {
    id: 'playlist--9dZXNouH4Agd0FJ',
    title: 'Lagu Untuk Membaca',
    fullname: 'hapi',
    songCount: '12',
    totalDuration: '450',
  },
  {
    id: 'playlist--9dZXNouH4Agd0djf',
    title: 'Lagu Tidur',
    fullname: 'thaetamii',
    songCount: '12',
    totalDuration: '250',
  },
  {
    id: 'playlist--erererererer343',
    title: 'Lagu Tidur',
    fullname: 'haeroni',
    songCount: '12',
    totalDuration: '150',
  },
  {
    id: 'playlist--9dZXNouH4Agd078weh',
    title: 'Lagu Kenyang',
    fullname: 'sujai',
    songCount: '12',
    totalDuration: '400',
  },
  {
    id: 'playlist--dkfeurieurerer',
    title: 'Subuh',
    fullname: 'gari',
    songCount: '12',
    totalDuration: '70',
  },
];

export const albumDetail = {
  id: 'album_john_1',
  title: 'Room for Squares',
  artist: 'John Mayer',
  year: 2001,
  coverUrl: 'https://picsum.photos/250/600',
  songCount: '5',
  totalDuration: '1137',
  songs: [
    {
      id: 'song_john_1',
      title: 'No Such Thing',
      performer: 'John Mayer',
      duration: 208,
      coverUrl: 'https://picsum.photos/100/300',
    },
    {
      id: 'song_john_2',
      title: 'Why Georgia',
      performer: 'John Mayer',
      duration: 243,
      coverUrl: 'https://picsum.photos/120/300',
    },
    {
      id: 'song_john_3',
      title: 'My Stupid Mouth',
      performer: 'John Mayer',
      duration: 223,
      coverUrl: 'https://picsum.photos/130/300',
    },
    {
      id: 'song_john_4',
      title: 'Neon',
      performer: 'John Mayer',
      duration: 225,
      coverUrl: 'https://picsum.photos/140/300',
    },
    {
      id: 'song_john_5',
      title: 'City Love',
      performer: 'John Mayer',
      duration: 238,
      coverUrl: 'https://picsum.photos/150/300',
    },
  ],
};

export const song = {
  id: 'song_john_1',
  title: 'No Such Thing',
  year: 2001,
  performer: 'John Mayer',
  genre: 'Pop Rock',
  duration: 208,
  coverUrl: 'https://picsum.photos/100/300',
  uploader: 'John Mayer',
  likes: ['John Mayer', 'Adele Laurie'],
  album: {
    id: 'album_john_1',
    title: 'Room for Squares',
    year: 2001,
    coverUrl: 'https://picsum.photos/250/600',
    uploader: 'John Mayer',
  },
};
