export const albums = [
  {
    id: 1,
    title: 'SOS',
    artist: 'SZA',
    cover: 'https://picsum.photos/200/600',
    songs: 23,
    duration: '68 min',
    likes: 1200000,
  },
  {
    id: 2,
    title: 'The Record',
    artist: 'Boygenius',
    cover: 'https://picsum.photos/300/600',
    songs: 12,
    duration: '42 min',
    likes: 450000,
  },
  {
    id: 3,
    title: 'Guts',
    artist: 'Olivia Rodrigo',
    cover: 'https://picsum.photos/220/600',
    songs: 12,
    duration: '39 min',
    likes: 980000,
  },
  {
    id: 4,
    title: 'Let’s Start Here',
    artist: 'Lil Yachty',
    cover: 'https://picsum.photos/600/600',
    songs: 14,
    duration: '57 min',
    likes: 320000,
  },
  {
    id: 5,
    title: 'Fountain Baby',
    artist: 'Amaarae',
    cover: 'https://picsum.photos/250/600',
    songs: 14,
    duration: '45 min',
    likes: 180000,
  },
  {
    id: 6,
    title: 'False Lankum',
    artist: 'Lankum',
    cover: 'https://picsum.photos/280/600',
    songs: 12,
    duration: '66 min',
    likes: 95000,
  },
  {
    id: 7,
    title: 'The Rise and Fall of a Midwest Princess',
    artist: 'Chappell Roan',
    cover: 'https://picsum.photos/270/600',
    songs: 14,
    duration: '49 min',
    likes: 600000,
  },
  {
    id: 8,
    title: 'Sundial',
    artist: 'Noname',
    cover: 'https://picsum.photos/290/600',
    songs: 11,
    duration: '33 min',
    likes: 130000,
  },
  {
    id: 9,
    title: 'DeBí TiRAR MáS FOToS',
    artist: 'Bad Bunny',
    cover: 'https://picsum.photos/310/600',
    songs: 17,
    duration: '60 min',
    likes: 1500000,
  },
  {
    id: 10,
    title: 'If You Asked for a Picture',
    artist: 'Blondshell',
    cover: 'https://picsum.photos/320/600',
    songs: 9,
    duration: '36 min',
    likes: 85000,
  },
  {
    id: 11,
    title: 'Tsunami Sea',
    artist: 'Spiritbox',
    cover: 'https://picsum.photos/330/600',
    songs: 10,
    duration: '40 min',
    likes: 110000,
  },
  {
    id: 12,
    title: 'Sable, Fable',
    artist: 'Bon Iver',
    cover: 'https://picsum.photos/340/600',
    songs: 12,
    duration: '50 min',
    likes: 300000,
  },
];

export const songs = [
  {
    id: 1,
    title: 'Not Like Us',
    artist: 'Kendrick Lamar',
    album: 'GNX',
    duration: '4:34',
    cover: 'https://picsum.photos/100/300',
  },
  {
    id: 2,
    title: 'Luther',
    artist: 'Kendrick Lamar feat. SZA',
    album: 'GNX',
    duration: '4:12',
    cover: 'https://picsum.photos/200/300',
  },
  {
    id: 3,
    title: 'Messy',
    artist: 'Lola Young',
    album: 'This Wasn’t Meant For You Anyway',
    duration: '4:44',
    cover: 'https://picsum.photos/110/300',
  },
  {
    id: 4,
    title: 'APT.',
    artist: 'ROSÉ & Bruno Mars',
    album: 'Rosie',
    duration: '2:59',
    cover: 'https://picsum.photos/130/300',
  },
  {
    id: 5,
    title: 'Die With A Smile',
    artist: 'Lady Gaga & Bruno Mars',
    album: 'LG7',
    duration: '3:15',
    cover: 'https://picsum.photos/140/300',
  },
  {
    id: 6,
    title: 'Denial Is A River',
    artist: 'Doechii',
    album: 'Alligator Bites Never Heal',
    duration: '4:09',
    cover: 'https://picsum.photos/150/300',
  },
  {
    id: 7,
    title: 'Good Luck, Babe!',
    artist: 'Chappell Roan',
    album: 'The Rise and Fall of a Midwest Princess',
    duration: '3:38',
    cover: 'https://picsum.photos/160/300',
  },
  {
    id: 8,
    title: 'Pink Pony Club',
    artist: 'Chappell Roan',
    album: 'The Rise and Fall of a Midwest Princess',
    duration: '4:18',
    cover: 'https://picsum.photos/170/300',
  },
  {
    id: 9,
    title: 'Baile Inolvidable',
    artist: 'Bad Bunny',
    album: 'Debí Tirar Más Fotos',
    duration: '3:50',
    cover: 'https://picsum.photos/180/300',
  },
  {
    id: 10,
    title: 'Nokia',
    artist: 'Drake feat. PartyNextDoor',
    album: 'Some Sexy Songs 4 U',
    duration: '3:22',
    cover: 'https://picsum.photos/190/300',
  },
  {
    id: 11,
    title: 'Ordinary',
    artist: 'Alex Warren',
    album: 'Ordinary',
    duration: '3:03',
    cover: 'https://picsum.photos/200/300',
  },
  {
    id: 12,
    title: 'Sports Car',
    artist: 'Tate McRae',
    album: 'Sports Car',
    duration: '3:10',
    cover: 'https://picsum.photos/210/300',
  },
  {
    id: 13,
    title: 'Burning Blue',
    artist: 'Mariah The Scientist',
    album: 'Burning Blue',
    duration: '3:25',
    cover: 'https://picsum.photos/220/300',
  },
  {
    id: 14,
    title: 'Tweaker',
    artist: 'LiAngelo Ball',
    album: 'Tweaker',
    duration: '2:55',
    cover: 'https://picsum.photos/230/300',
  },
  {
    id: 15,
    title: 'Anxiety',
    artist: 'Doechii',
    album: 'Alligator Bites Never Heal',
    duration: '4:09',
    cover: 'https://picsum.photos/240/300',
  },
  {
    id: 16,
    title: 'Café Con Ron',
    artist: 'Bad Bunny feat. Pleneros de la Cresta',
    album: 'Debí Tirar Más Fotos',
    duration: '3:40',
    cover: 'https://picsum.photos/250/300',
  },
  {
    id: 17,
    title: 'I’m The Problem',
    artist: 'Morgan Wallen feat. Tate McRae',
    album: 'I’m The Problem',
    duration: '3:05',
    cover: 'https://picsum.photos/270/300',
  },
  {
    id: 18,
    title: 'The Giver',
    artist: 'Chappell Roan',
    album: 'The Giver',
    duration: '3:30',
    cover: 'https://picsum.photos/260/300',
  },
  {
    id: 19,
    title: 'Crybaby',
    artist: 'SZA',
    album: 'Lana',
    duration: '3:45',
    cover: 'https://picsum.photos/270/300',
  },
  {
    id: 20,
    title: 'Esa Noche',
    artist: 'Eslabón Armado feat. Macario Martínez',
    album: 'Vibras de Noche II',
    duration: '4:00',
    cover: 'https://picsum.photos/290/300',
  },
  {
    id: 21,
    title: 'Rather Lie',
    artist: 'Playboi Carti feat. The Weeknd & Keith Lawson',
    album: 'Music',
    duration: '3:20',
    cover: 'https://picsum.photos/400/300',
  },
  {
    id: 22,
    title: 'Nice to Each Other',
    artist: 'Olivia Dean',
    album: 'Messy',
    duration: '3:15',
    cover: 'https://picsum.photos/222/300',
  },
];
